name: build-and-push-ghcr

on:
  push:
    branches: ['main']
    paths:
      - 'Dockerfile.api'
      - 'Dockerfile.web'
      - 'apps/**'
      - '.github/workflows/docker-ghcr.yml'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.api
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nelaya-api:latest
            ghcr.io/${{ github.sha }}

  build-web:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.web
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/nelaya-web:latest
            ghcr.io/${{ github.sha }}
